name: admin_zp
version: 1.0.0+1
publish_to: none
description: Admin app for ZestyPantry
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: 4.8.4
  firebase_core: 2.15.0
  fluttertoast: 8.2.2
  firebase_messaging: 14.6.5
  flutter_local_notifications: 15.1.0+1
  firebase_admin: ^0.2.0
  http: 0.13.0
  firebase_auth: 4.7.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

